test: add test_save_to_file test function
napalmpapalam/keep-a-changelog-rs pull request #2
Opened 2024-05-21 15:08 UTC by gortavoher

Simple test which expects that the changelog to be unchanged when opened and saved back.
* chore(.gitignore): add **/tmp to .gitignore
* test(changelog.rs): add test_save_to_file test function
* test: add basic_changelog.md file test data file

2024-05-23 06:46 UTC, napalmpapalam requested changes

2024-05-23 06:46 UTC, napalmpapalam commented on src/changelog.rs
> +
```suggestion
    /// Format the changelog as a string for output as a valid Markdown file
    ///
    /// To ensure compliance with the requirements of the Markdown standard any blank
    /// line at the end of the string needs to be removed.
    ///
    fn file_contents(&self) -> String {
        if !self.to_string().ends_with("\n\n") {
            return self.to_string();
        }
        
        let mut s = self.to_string().trim_end_matches('\n').to_string();
        s.push('\n');
        s
    }

```

2024-05-23 06:46 UTC, napalmpapalam commented on tests/data/initial_changelog_unreleased.md
> +- Initial commit
Please, add your changes to the `CHANGELOG.md` file. Nice work btw.

2024-05-23 07:17 UTC, napalmpapalam commented
Also, could you please make it configurable to add an empty line after the heading 🙏 ?  I understand that it's a best practice, but I stick to not adding it to my projects, coz I like it, it's more readable for me. It could be added by default, but there should be the ability to switch this behavior

2024-05-23 08:54 UTC, jerusdp commented
> Also, could you please make it configurable to add an empty line after the heading 🙏 ? I understand that it's a best practice, but I stick to not adding it to my projects, coz I like it, it's more readable for me. It could be added by default, but there should be the ability to switch this behavior

So the default is to keep the markdownlint quite but a feature setting to allow the non-compliant "compact" format.  This will need:
- [ ] Documentation to describe the feature and its impact
- [ ] Tests to validate that it works as expected
- [ ] Feature gated implementation to meet the test. 

As part of this release or as an enhancement?

2024-05-23 10:41 UTC, napalmpapalam commented
> > Also, could you please make it configurable to add an empty line after the heading 🙏 ? I understand that it's a best practice, but I stick to not adding it to my projects, coz I like it, it's more readable for me. It could be added by default, but there should be the ability to switch this behavior
> 
> So the default is to keep the markdownlint quite but a feature setting to allow the non-compliant "compact" format. This will need:
> 
> * [ ]  Documentation to describe the feature and its impact
> * [ ]  Tests to validate that it works as expected
> * [ ]  Feature gated implementation to meet the test.
> 
> As part of this release or as an enhancement?

As I see, we can add [here](https://github.com/napalmpapalam/keep-a-changelog-rs/blob/master/src/changelog.rs#L54) one more option, for example, `compact: bool` and the changelog will be formatted relative to it, everything else seems fine. It could be part of this PR.

2024-05-24 06:59 UTC, jerusdp commented
Ok, let me take a crack at it :smiley:

2024-05-25 05:43 UTC, jerusdp commented
@napalmpapalam  what is the purpose of the '$' in this code for the writing flags?

```rust
       if let Some(flag) = self.flag.clone() {
            writeln!(f, "<!-- ${flag} -->")?;
        }
```

2024-05-25 07:06 UTC, napalmpapalam commented
> @napalmpapalam  what is the purpose of the '$' in this code for the writing flags?
> 
> 
> 
> ```rust
> 
>        if let Some(flag) = self.flag.clone() {
> 
>             writeln!(f, "<!-- ${flag} -->")?;
> 
>         }
> 
> ```
> 
> 
> 
> 

It's a bug. Plz remove it. I probably missed that thing during rewriting from JS

2024-06-07 07:20 UTC, napalmpapalam commented
@gortavoher hey, lemme know (tag me) when u want I will review it, plz

2024-06-07 13:15 UTC, jerusdp commented
> @gortavoher hey, lemme know (tag me) when u want I will review it, plz

@napalmpapalam  Good for review now, thanks.

2024-06-08 04:51 UTC, napalmpapalam approved these changes

2024-06-08 04:51 UTC, merged